[icons]
#font-awesome
firefox = ""
St = ""
Steam = ""
discord = ""
jetbrains-studio = ""
Spotify = ""
Emacs = ""
Zathura = ""
code-oss = ""
Nextcloud = ""
tidal-hifi = ""
Sxiv = ""
processing-app-Base = ""
Ferdi = ""

[aliases]
jetbrains-studio = "Android Studio"
discord = "Discord"
firefox = "Firefox"
St = "st"
code-oss = "Code"
tidal-hifi = "Tidal"
Sxiv = "sxiv"
processing-app-Base = "Arduino"

[general]
separator = " | "
