[icons]
#font-awesome
firefox = "ï‰©"
St = "ï‹"
Steam = "ï†¶"
discord = "ï’"
jetbrains-studio = "ï…»"
Spotify = "ï†¼"
Emacs = "ï‡‰"
Zathura = "ï‡"
code-oss = "ï‡‰"
Nextcloud = "ïƒ‚"
tidal-hifi = "ğŸŒŠ"
Sxiv = "ïŒ‚"

[aliases]
jetbrains-studio = "Android Studio"
discord = "Discord"
firefox = "Firefox"
St = "st"
code-oss = "Code"
tidal-hifi = "Tidal"
Sxiv = "sxiv"
